name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres_container:
        image: postgres:17.4-alpine3.21
        env:
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432  # Изменено с 5433 на 5432
        options: >-
          --health-cmd "pg_isready -U ${{ vars.POSTGRES_USER }} -d ${{ vars.POSTGRES_DB }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      chroma-server:
        image: chromadb/chroma:latest
        ports:
          - 8000:8000

      fore-ai-backend:
        image: michaloni/foreai:v1
        ports:
          - 80:80
        env:
          DATABASE_CONNECTION_STRING: postgresql://admin:admin@localhost:5432/foreaidb  # Используем имя контейнера
          CHROMA_HOST: ${{ vars.CHROMA_HOST }}
          CHROMA_PORT: ${{ vars.CHROMA_PORT }}
        options: >-
          --health-cmd "curl --fail http://localhost:80/docs || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Wait for PostgreSQL to be Ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        until PGPASSWORD=${{ vars.POSTGRES_PASSWORD }} psql -h postgres_container -U ${{ vars.POSTGRES_USER }} -d ${{ vars.POSTGRES_DB }} -c '\q'; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done
        echo "PostgreSQL is ready!"

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Backend to be Ready
      run: |
        echo "Waiting for backend to be ready..."
        until curl --silent --fail http://localhost:80/docs; do
          echo "Waiting for backend..."
          sleep 5
        done
        echo "Backend is ready!"

    - name: Run Tests
      env:
        BASE_URL: "http://localhost:80"
      run: |
        pytest tests/
